services:
  - type: web
    name: gymtracker-pro
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: "http://localhost:5173" # Also add your Vercel URL in Render dashboard
      - key: MONGODB_URI
        value: "mongodb+srv://kjayeshrao_db_user:b7v8uV8qTLxyUVyj@cluster0.qjdugqh.mongodb.net/gymtracker?appName=Cluster0"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: COOKIE_SECRET
        generateValue: true
